# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = systemd-run --user --no-block bash ~/.config/waybar/claude-workspace-watcher.sh
exec-once = systemd-run --user --no-block bash ~/.config/waybar/notification-watcher.sh
exec-once = uwsm-app -- zen-browser
exec-once = uwsm-app -- bitwarden-desktop
exec-once = [workspace 2 silent] ghostty --working-directory="$(/usr/bin/zoxide query creditcard)"
exec-once = [workspace 3 silent] ghostty --working-directory="$(/usr/bin/zoxide query gitops)"
exec-once = [workspace 4 silent] ghostty --working-directory=~/.local/share/chezmoi/
