[colors.primary]
background = "#FFFCF0"
foreground = "#100F0F"

[colors.cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.vi_mode_cursor]
text = "#FFFCF0"
cursor = "#100F0F"

[colors.search.matches]
foreground = "#FFFCF0"
background = "#D0A215"

[colors.search.focused_match]
foreground = "#FFFCF0"
background = "#D14D41"

[colors.footer_bar]
foreground = "#FFFCF0"
background = "#100F0F"

[colors.selection]
text = "#100F0F"
background = "#CECDC3"

[colors.normal]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#205EA6"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

[colors.bright]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"
