return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "cmakelang",
        "cmakelint",
        "copilot-language-server",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "hadolint",
        "helm-ls",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "markdown-toc",
        "marksman",
        "neocmakelsp",
        "phpactor",
        "phpcs",
        "php-cs-fixer",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "taplo",
        "terraform-ls",
        "tflint",
        "twigcs",
        "twig-cs-fixer",
        "twiggy-language-server",
        "yaml-language-server",
      },
    },
  },
}
