-- Intentionally empty.
-- Link icon removal attempts are no longer needed (icons are acceptable).
-- obsidian.nvim UI is disabled in plugins/obsidian.lua to fix the icon
-- race condition with render-markdown. Spacing is handled by Ghostty's
-- default unicode width rendering plus render-markdown's overflow detection.
